name: Release

on:
    push:
        tags:
            - 'v*'

defaults:
    run:
        shell: bash

jobs:
    linux:
        name: Linux
        runs-on: ubuntu-20.04
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   uses: actions/setup-dotnet@v1.8.1
                with:
                    dotnet-version: 6.0.x
            -   name: NuGet Auth
                uses: StirlingLabs/GithubNugetAuthAction@main
            -   name: Build
                run: dotnet build sockaddr.Net.sln -c Release
            -   name: Test
                run: dotnet test sockaddr.Net.sln --no-build -c Release --logger GitHubActions
            -   name: Save coverage to storage branch
                uses: StirlingLabs/BranchStorageAction@v21.07.3
                with:
                    comment: |
                        Coverage for ${{github.ref}}
                        Action: https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}
                        Commit: https://github.com/${{github.repository}}/commit/${{github.sha}}
                    storage-branch: coverage
                    src: coverage
                    dst: coverage
                    prune: true
            -   name: Pack
                run: dotnet pack sockaddr.Net.sln --no-restore --no-build -c Release --output artifacts
            -   name: Artifacts
                uses: actions/upload-artifact@v2
                with:
                    name: sockaddr.Net
                    path: |
                        artifacts/*.nupkg
                        coverage
                    if-no-files-found: error
    
    macos:
        name: Mac
        runs-on: macos-11
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   uses: actions/setup-dotnet@v1.8.1
                with:
                    dotnet-version: 6.0.x
            -   name: Test
                run: dotnet test sockaddr.Net.sln -c Release --logger GitHubActions

    windows:
        name: Windows
        runs-on: windows-2022
        steps:
            -   uses: actions/checkout@v2
                with:
                    submodules: true
            -   name: Fetch tag git metadata
                run: git fetch --force --update-shallow --depth 1 origin +refs/tags/*:refs/tags/* || echo no tags
            -   uses: actions/setup-dotnet@v1.8.1
                with:
                    dotnet-version: 6.0.x
            -   name: Test
                run: dotnet test sockaddr.Net.sln -c Release --logger GitHubActions

    create_release:
        name: Create Release
        runs-on: ubuntu-20.04
        needs: [ linux, macos, windows ]
        steps:
            -   uses: actions/download-artifact@v2
                with:
                    path: artifacts
            -   name: Create Release
                uses: softprops/action-gh-release@v0.1.12
                with:
                    name: sockaddr.Net
                    files: |
                        artifacts/**
